name: Formats

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Format PHP 8.2

    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        shell: bash
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-php-8.2-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-php-8.2-composer-

      - name: Install Composer dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Check code style
        run: vendor/bin/pint --test

      - name: Check refactor
        run: vendor/bin/rector --dry-run

      - name: Run static analysis
        run: vendor/bin/phpstan --no-progress